language: perl
perl:
  - "5.30"
env:
  - AUTHOR_TESTING=1 RELEASE_TESTING=1 PERL_CPANM_OPT="--quiet --notest"
cache:
  directories:
    - ${PERLBREW_ROOT}/perls/${PERLBREW_PERL}/lib
    - ${PERLBREW_ROOT}/perls/${PERLBREW_PERL}/bin
before_install:
  - cpanm Perl::Critic
  - perlcritic --quiet --single-policy=RequireTidyCode bin
  - dzil authordeps --missing | cpanm
  - dzil listdeps --author --missing | cpanm
  - cpanm DBI IPC::Shareable Parallel::ForkManager Digest::HMAC_SHA1
  - cpanm String::Escape XML::LibXML Net::SFTP::Foreign IO::Pty Test::mysqld
install:
  - dzil build --in build --notgz
script:
  - cd build && prove --timer --lib --recurse --jobs $(nproc) --shuffle t/ xt/

jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - rm /bin/perl
        - cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
        - export "PERL5LIB=/c/Strawberry/perl/site/lib:/c/Strawberry/perl/site/lib:/c/Strawberry/perl/vendor/lib:/c/Strawberry/perl/lib"
        - export "AUTHOR_TESTING=1"
        - export "RELEASE_TESTING=1"
        - export "PERL_CPANM_OPT='--quiet --notest'"
        - ln -s /c/Strawberry/perl/bin/perl /bin/perl
        - cpanm Perl::Critic
        - perlcritic --quiet --single-policy=RequireTidyCode bin
        - cpanm --reinstall --verbose Module::Pluggable::Object
        - cpanm Dist::Zilla
        - dzil authordeps --missing | cpanm
        - dzil listdeps --author --missing | cpanm
        - cpanm DBI Parallel::ForkManager Digest::HMAC_SHA1
        - cpanm String::Escape XML::LibXML Net::SFTP::Foreign Test::mysqld
        - cpanm --reinstall --verbose App::Prove
      install:
        - dzil build --in build --notgz
      script:
        - cd build
        - prove --timer --lib --recurse --jobs 9 --shuffle t/
